name: smart_sun
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  jwt_decode: ^0.3.1
  shared_preferences: ^2.0.15
  http:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/SMART.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-VariableFont_wght.ttf
